# Generated by Django 5.2 on 2025-04-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='CJQpysHUZ1JXbIkdJBZPRn1o4rQsmLq5', editable=False, max_length=32, unique=True),
        ),
    ]
