# Generated by Django 5.2 on 2025-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='wtlpuycZucFlz6v0nU1gAF0dFfd2LbzV', editable=False, max_length=32, unique=True),
        ),
    ]
