# Generated by Django 5.2 on 2025-04-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='A7wh7OG20g2nOPbWDb4bNidna9YYOwX0', editable=False, max_length=32, unique=True),
        ),
    ]
