# Generated by Django 5.2 on 2025-04-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='GcyDZXhnHZAvMiJPkx1o4h77EM6Av5h9', editable=False, max_length=32, unique=True),
        ),
    ]
