# Generated by Django 5.2 on 2025-04-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='DiHfEqtgQ2cw61SaqkEBs23sWzA4eHhD', editable=False, max_length=32, unique=True),
        ),
    ]
