# Generated by Django 5.2 on 2025-04-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='bb7XHNeHtROczqjZ3uFLYlyDwGUteOXL', editable=False, max_length=32, unique=True),
        ),
    ]
